version: 0.2
phases:
install:
   commands:
      -  apt install docker.io
 pre_build:
    commands:
      - echo pre_build step.... 
      - docker login -username $DOCKER_USERNAME -password $DOCKER_PASSWORD
 build:
    commands:
      - docker build -t viraj5132/krima:latest .
      - docker push viraj5132/krima:latest
      - scp -o StrictHostKeyChecking=no nodejs.yml bluetraffic.sh ubuntu@$DEPLOY_IP:/home/ubuntu/node-app-1
      - ssh ubuntu@$DEPLOY_IP kubectl rollout restart deployment green
  build:
    commands:
      - echo staring switch traffic to blue
     
  post_build:
    commands:
      - ssh ubuntu@$DEPLOY_IP \'chmod 777 bluetraffic.sh && ./bluetraffic.sh\'
artifacts:
  files:
    - '**/*'
