version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - cd ~/.ssh
      - ls
      - echo -n "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa && chmod 0400 ~/.ssh/id_rsa
#       - aws --version
#       - docker -v
#       - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
#       - REPOSITORY_URI=017690734226.dkr.ecr.ap-south-1.amazonaws.com/node-app
#   build:
#     commands:
#       - echo Build started on `date`
#       - echo Building the Docker image.
#       - docker build -t $REPOSITORY_URI:latest .
#   post_build:
#     commands:
#       - echo Build completed on `date`
#       - echo Pushing the Docker images...
#       - docker push $REPOSITORY_URI:latest

