version: 0.1

phases:
  pre_build:
    commands:
      - \$(docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD)
  build:
    commands:
      - docker build -t viraj5132/krima:latest .
      - docker push viraj5132/krima:latest
      - scp -o StrictHostKeyChecking=no nodejs.yml bluetraffic.sh ubuntu@$DEPLOY_IP:/home/ubuntu/node-app-1
      - ssh ubuntu@$DEPLOY_IP kubectl rollout restart deployment green
  build:
    commands:
      - echo staring switch traffic to blue
     
  post_build:
    commands:
      - ssh ubuntu@$DEPLOY_IP \'chmod 777 bluetraffic.sh && ./bluetraffic.sh\'
artifacts:
  files:
    - '**/*'
