version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo building docker image
      - docker build -t node-app .
      - docker tag node-app:latest 017690734226.dkr.ecr.ap-south-1.amazonaws.com/node-app:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 017690734226.dkr.ecr.ap-south-1.amazonaws.com/node-app:latest
artifacts:
  files:
    - '**/*'
